services:
  migrate:
    build: .
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - identity_service_network

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - identity_service_network

  worker:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - identity_service_network

  beat:
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - identity_service_network

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - identity_service_network

  mailpit:
    image: axllent/mailpit:latest
    networks:
      - identity_service_network
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:7-alpine
    user: "redis"
    networks:
      - identity_service_network
    volumes:
      - redis_data:/data
    command: >
      redis-server
        --appendonly yes
        --appendfsync everysec
        --maxmemory 256mb
        --loglevel notice
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

networks:
  identity_service_network:
    driver: bridge
    internal: false

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
